### ISSUE TITLE
Projeto

### ISSUE THREAD

**Issue by DjRafael50** [jailsonsb2/Radioplayer_api#2]
Olá amigo, você poderia fazer codigo que mostra o histórico de musica, estilo https://hunter.fm/master ou https://vagalume.fm/nostalgia-anos-2000/. Gostaria muito de melhorar minhas estações https://onbeat.top/ mas não sei como fazer, quanto você cobraria para fazer se puder. Abraço

**Comment by jailsonsb2** [comment]
me chame no meu e-mail contato@jailson.es, que eu faço para você sim!

**Comment by DjRafael50** [comment]
Obrigado meu amigo, ja te enviei.
