### ISSUE TITLE
Olá 

### ISSUE THREAD

**Issue by DjRafael50** [jailsonsb2/Radioplayer_api#3]
Boa noite grande Jailson, estava olhando no código e vi que tem [POP-UP DE INÍCIO E HANDLERS] como adiciono na aplicação, ele tem como usar com Vast, a pessoa tem que assistir um vídeo ad e depois começa a executar o player?

Obrigado desde já 🙂

**Comment by jailsonsb2** [comment]
Era um codigo antigo mas sim é possivel!

**Comment by DjRafael50** [comment]
> Era um codigo antigo mas sim é possivel!

Eu até consegui, mas ou menos, usando IA ehehee pois sou burro e não entendo muito, o unico problema é que o player não volta automaticamente, se você quizer eu te envio o código gerado para vc ver.

Grande abraço, fica com Deus.
